# lambda max memory
lambdaReverseGeocodingMaxMemory: 
  Type: "AWS::Logs::MetricFilter"
  Properties: 
    LogGroupName: /aws/lambda/lambda-reverse-geocoding-${opt:stage}
    FilterPattern: '[report_name="REPORT", request_id_name="RequestId:", request_id_value,
      duration_name="Duration:", duration_value, duration_unit="ms", billed_duration_name_1="Billed",
      bill_duration_name_2="Duration:", billed_duration_value, billed_duration_unit="ms",
      memory_size_name_1="Memory", memory_size_name_2="Size:", memory_size_value, memory_size_unit="MB",
      max_memory_used_name_1="Max", max_memory_used_name_2="Memory", max_memory_used_name_3="Used:",
      max_memory_used_value, max_memory_used_unit="MB"]'
    MetricTransformations: 
    - MetricName: Max_memory_Reverse_geocoding_${opt:stage}
      MetricNamespace: "CadLambda/Memory"
      MetricValue: $max_memory_used_value