service: http-codes-api

provider:
  name: aws
  runtime: java8
  region: eu-west-1
  timeout: 10
  memorySize: 256
 
package:
  artifact: target/http-codes.jar
  
custom:
  stageName: ${opt:stage}
  dynamoTable: httpCodeStatistics
        
functions:
  #######
  configuration:
    handler: devoxx.serverless.api.ConfigurationGetHandler
    role: lambdaConfigurationRole
    events:
      - http:
          private: true
          method: get
          path: configuration/
          cors: true
  ######
  getCodes:
    handler: devoxx.serverless.api.CodeStatisticsGetHandler
    role: lambdaGetCodesRole
    environment:
      TARGET_DYNAMO_TABLE_NAME: ${self:custom.dynamoTable}
    events:
      - http:
          private: true
          path: codes
          method: get
          cors: true
    ######
  putCode:
    handler: devoxx.serverless.api.CodePutHandler
    role: lambdaPutCodeRole
    environment:
      TARGET_DYNAMO_TABLE_NAME: ${self:custom.dynamoTable}
    events:
      - http:
          private: true
          path: code/{code}
          method: put
          cors: true
resources:
  Resources:
### dynamo ###
    httpCodesDynamoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: HttpCodeStatistics
        AttributeDefinitions:
        - AttributeName: code
          AttributeType: N
        KeySchema:
        - AttributeName: code
          KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 100
          WriteCapacityUnits: 100
### Roles ####
    lambdaConfigurationRole: ${file(./serverless.d/roles.yml):lambdaConfigurationRole}
    lambdaGetCodesRole: ${file(./serverless.d/roles.yml):lambdaGetCodesRole}
    lambdaPutCodeRole: ${file(./serverless.d/roles.yml):lambdaPutCodeRole}